apiVersion: apps/v1
kind: Deployment
metadata:
  name: meet
  labels:
    app: meet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meet
  template:
    metadata:
      labels:
        app: meet
    spec:
      containers:
        - name: meet
          image: docker_user/docker_project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secret-meet
                  key: db_database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-meet
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-meet
                  key: db_password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-meet
                  key: db_port
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: secret-meet
                  key: db_server
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-meet
                  key: mail_host
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-meet
                  key: mail_port
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: secret-meet
                  key: mail_user
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-meet
                  key: mail_password
            - name: APPLICATION_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-meet
                  key: application_host