apiVersion: v1
kind: Service
metadata:
  name: svc-meet
  labels:
    app: meet
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: meet